# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache:
  packages: true
  directories:
  - ~/.ccache
  
warnings_are_errors: true

install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install ccache; export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export PATH="/usr/lib/ccache:$PATH"; fi

branches:
  only:
  - TravisTests

os:
  - linux
  - osx
osx_image: xcode9 


env:
  global: 
    - RGL_USE_NULL=TRUE
    - PROJECT_NAME=neuroconductor
    - DISPLAY=:99.0
    - R_CHECK_ARGS="--as-cran --install-args=--build"
    - WARNINGS_ARE_ERRORS=1 

before_install:
  - ulimit -n 2048
  - export PROJ_DIR=`basename $PWD`    
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}  
  - cat DESCRIPTION
  - export PACKAGE_NAME=`package_name`
  - echo "Package Name is $PACKAGE_NAME"
  - export cmake_version="3.11"
  - cmake --version
  - x=`cmake_setup`; echo "${x}"; eval ${x};
  - cmake --version  
  - rhome=`R RHOME`; echo ${rhome}; ls ${rhome};

script:
  # - source ~/.R/Makevars
  - x=`export_clang_cxx`; eval ${x}
  - travis_wait 3 R CMD build ${R_BUILD_ARGS} . 
  - rm -f travis_wait*.log
  - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
  - ls
  - export MAKEJ=3 
  - travis_wait 49 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
  - rm -f travis_wait*.log
  - if [[ $CHECK_RET -ne 0 ]];
    then
      echo "R CMD check failed"; 
      check_fail; 
      dump_logs; 
      travis_terminate 1;
    fi  
  - check_warnings

after_success:
  - dump_logs

after_failure:
  - dump_logs
  - cat SimpleITK.Rcheck/00install.out
