trigger:
- master

jobs:
  - job: Linux
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 300
    pool:
      vmImage: 'Ubuntu-22.04'

    steps:
      - checkout: self
        clean: true
        fetchDepth: 5
      - bash: |
          set -x
          if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
            git checkout $(System.PullRequest.SourceCommitId)
          fi
      - bash: |
          set -x
          df -h
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libssh2-1-dev libharfbuzz-dev libfribidi-dev gh
        displayName: System Dependencies
        workingDirectory: $(Agent.BuildDirectory)
      - bash: |
          set -x
          mkdir ${R_LIBS}
          df -h
          R -e "install.packages(c('git2r', 'devtools'), lib=c('${R_LIBS}'), repo='https://cloud.r-project.org/')"
        displayName: 'Intall R packages'
        env:
          R_LIBS: $(Agent.WorkFolder)/Rlibs
        workingDirectory: $(Agent.BuildDirectory)
      - bash: |
          set -x
          c++ --version
          cmake --version
          which R
          R --version
          df -h
          R -e "devtools::install(c('$(Build.SourcesDirectory)'), lib=c('${R_LIBS}'), args=c('--configure-vars="MAKEJ=2"'))"
        displayName: Build and test
        env:
          ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS: 2
          R_LIBS: $(Agent.WorkFolder)/Rlibs
        workingDirectory: $(Agent.BuildDirectory)
  - job: macOS
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 300
    pool:
      vmImage: 'macOS-latest'

    steps:
      - checkout: self
        clean: true
        fetchDepth: 5
      - bash: |
          set -x
          if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
            git checkout $(System.PullRequest.SourceCommitId)
          fi
      - bash: |
          set -x
          curl -L https://cran.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.3.1-x86_64.pkg -o R.pkg
          sudo installer -pkg R.pkg -target /
          mkdir ${R_LIBS}
          R -e "install.packages(c('git2r', 'devtools'), lib=c('${R_LIBS}'), repo='http://cloud.r-project.org/')"
        displayName: 'Intall R and packages'
        workingDirectory: $(Agent.BuildDirectory)
        env:
          R_LIBS: $(Agent.WorkFolder)/Rlibs
      - bash: |
          set -x
          c++ --version
          cmake --version
          which R
          R --version
          R -e "devtools::install(c('$(Build.SourcesDirectory)'), lib=c('${R_LIBS}'), args=c('--configure-vars="MAKEJ=2"'))"
          df -h
        displayName: Build and test
        env:
          R_LIBS: $(Agent.WorkFolder)/Rlibs
          ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS: 2
        workingDirectory: $(Agent.BuildDirectory)
