trigger:
- master

resources:
  repositories:
    - repository: r-azure-pipelines
      type: github
      name: r-lib/r-azure-pipelines
      endpoint: r-lib

parameters:
  R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
  CRAN: 'https://cloud.r-project.org'
  coverage: true
  env: {}
  
jobs:
  - job: Windows
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 10
    variables:
      CRAN: ${{parameters.CRAN}}
      R_LIBS_USER: ${{parameters.R_LIBS_USER}}
      CI: true
      ${{ insert }}: ${{ parameters.env }}
    pool:
      vmImage: 'windows-latest'

    steps:
      - template: templates/r-setup-windows.yml
      - checkout: self
        clean: true
        fetchDepth: 5
      - bash: |
          set -x
          if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
            git checkout $(System.PullRequest.SourceCommitId)
          fi
        displayName: GitCheckout

