trigger:
- master

jobs:
  - job: Linux
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 300
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - checkout: self
        clean: true
        fetchDepth: 5
      - bash: |
          set -x
          if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
            git checkout $(System.PullRequest.SourceCommitId)
          fi
      - bash: |
          set -x
          sudo apt-get update
          sudo apt-get -y install software-properties-common libcurl4-openssl-dev libssh2-1-dev
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
          sudo add-apt-repository -y "deb https://cloud.r-project.org/bin/linux/ubuntu xenial/"
          sudo apt-get update
          sudo apt-get -y install r-base-dev
        displayName: System Dependencies
        workingDirectory: $(Agent.BuildDirectory)
      - bash: |
          set -x
          mkdir $(Agent.WorkFolder)/Rlibs
          R -e "install.packages('devtools', lib=c('${R_LIBS}'), repo='http://cloud.r-project.org/')"
        displayName: 'Intall R packages'
        workingDirectory: $(Agent.BuildDirectory)
        env:
          R_LIBS: $(Agent.WorkFolder)/Rlibs
      - bash: |
          set -x
          c++ --version
          cmake --version
          which R
          R --version
          R -e "withr::with_libpaths(c('${R_LIBS}'), devtools::install(c('$(Build.SourcesDirectory)'), args=c('--configure-vars=MAKEJ=2')))"
        displayName: Build and test
        env:
          R_LIBS: $(Agent.WorkFolder)/Rlibs
          ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS: 2
        workingDirectory: $(Agent.BuildDirectory)
  - job: macOS
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 300
    pool:
      vmImage: 'macOS-10.13'

    steps:
      - checkout: self
        clean: true
        fetchDepth: 5
      - bash: |
          set -x
          if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
            git checkout $(System.PullRequest.SourceCommitId)
          fi
      - bash: |
          set -x
          curl -L https://cran.cnr.berkeley.edu/bin/macosx/R-3.5.3.pkg -o R.pkg
          sudo installer -pkg R.pkg -target /
          mkdir $(Agent.WorkFolder)/Rlibs

          R -e "install.packages('https://cran.r-project.org/bin/macosx/el-capitan/contrib/3.5/git2r_0.26.0.tgz', lib=c('${R_LIBS}'), repo=NULL)"
          R -e "install.packages('devtools', lib=c('${R_LIBS}'), repo='http://cloud.r-project.org/')"
        displayName: 'Intall R and packages'
        workingDirectory: $(Agent.BuildDirectory)
        env:
          R_LIBS: $(Agent.WorkFolder)/Rlibs
      - bash: |
          set -x
          c++ --version
          cmake --version
          which R
          R --version
          R -e "devtools::install(c('$(Build.SourcesDirectory)'), lib=c('${R_LIBS}'), args=c('--configure-vars="MAKEJ=2"'))"
          df -h
        displayName: Build and test
        env:
          R_LIBS: $(Agent.WorkFolder)/Rlibs
          ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS: 2
        workingDirectory: $(Agent.BuildDirectory)
