trigger:
- master

jobs:
  - job: Windows
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 300
    pool:
      vmImage: 'windows-latest'

    steps:
      - checkout: self
        clean: true
        fetchDepth: 5
      - bash: |
          set -x
          if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
            git checkout $(System.PullRequest.SourceCommitId)
          fi
        displayName: Build and test
        env:
          R_LIBS: $(Agent.WorkFolder)/Rlibs
          ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS: 2
        workingDirectory: $(Agent.BuildDirectory)
