trigger:
- master

jobs:
  - job: Windows
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 300
    pool:
      vmImage: 'windows-latest'

    steps:
      - checkout: self
        clean: true
        fetchDepth: 5
      - bash: |
          set -x
          if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
            git checkout $(System.PullRequest.SourceCommitId)
          fi
        displayName: GitCheckout
      - bash: |
          set -x
          curl https://cloud.r-project.org/bin/windows/base/R-3.6.1-win.exe -o R-3.6.1-win.exe
          curl https://cloud.r-project.org/bin/windows/Rtools/Rtools35.exe -o Rtools35.exe
          ./R-3.6.1-win.exe /DIR="c:\Program Files\R" /GROUP="R" /COMPONENTS="main,x86_64,translations"
        displayName: RStuff
