

trigger:
- master

jobs:
  - job: Windows
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 10
    pool:
      vmImage: 'windows-latest'
# r installation from https://github.com/r-lib/r-azure-pipelines/
    steps:
      - pwsh: |
          choco install r.project -y --no-progress
          Invoke-WebRequest "https://github.com/hannesmuehleisen/choco-rtools/raw/master/rtools.3.5.0.nupkg" -OutFile "..\rtools.3.5.0.nupkg"
          choco install rtools -s ..\rtools.3.5.0.nupkg -f -y --no-progress
          choco install ninja
          # Set the timezone
          tzutil /s "GMT Standard Time"
        displayName: 'Installing R'
      - pwsh: |
          Write-Host "##vso[task.setvariable variable=PATH]C:\Rtools\bin;C:\Rtools\mingw_64\bin;${env:PATH};C:\Progra~1\R\R-3.6.1\bin"
        displayName: 'Setting PATH'
      - checkout: self
        clean: true
        fetchDepth: 5
      - bash: |
          set -x
          if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
            git checkout $(System.PullRequest.SourceCommitId)
          fi
        displayName: GitCheckout
      - bash: |
          set -x
          c++ --version
          cmake --version
          which R
          R --version
          R -e "devtools::install(c('$(Build.SourcesDirectory)'), lib=c('${R_LIBS}'), args=c('--configure-vars="MAKEJ=2"'))"
          df -h
        displayName: Build and test
        env:
          R_LIBS: $(Agent.WorkFolder)/Rlibs
          ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS: 2
        workingDirectory: $(Agent.BuildDirectory)

